import intf_libs += libcrails-encrypt%lib{crails-encrypt}
import intf_libs += libcrails-random%lib{crails-random}
import intf_libs += libcrails-controllers%lib{crails-controllers}

lib{crails-signin}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-signin}:
{
  cxx.export.poptions = "-I$out_root/libcrails-signin/" "-I$src_root/libcrails-signin/"
  cxx.export.libs = $intf_libs
}

liba{crails-signin}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-signin}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-signin}: bin.lib.version = "-$version.project_id"
else
  lib{crails-signin}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
